<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-2NB5M8O" name="Default test" tests="10" failures="1" timestamp="31 Aug 2019 12:50:01 GMT" time="43.692" errors="0">
  <testcase name="invalidEmailTest" time="0.877" classname="application.SignUpTest"/>
  <testcase name="noConfirmPasswordTest" time="0.888" classname="application.SignUpTest"/>
  <testcase name="noEmailTest" time="0.748" classname="application.SignUpTest"/>
  <testcase name="noFirstNameTest" time="0.824" classname="application.SignUpTest"/>
  <testcase name="noInputTest" time="0.321" classname="application.SignUpTest"/>
  <testcase name="noLastNameTest" time="2.234" classname="application.SignUpTest"/>
  <testcase name="noPasswordTest" time="0.88" classname="application.SignUpTest"/>
  <testcase name="passwordMismathwithConfirmPasswordTest" time="0.941" classname="application.SignUpTest"/>
  <testcase name="shortPasswordTest" time="0.89" classname="application.SignUpTest"/>
  <testcase name="createAccountSuccessTest" time="5.839" classname="application.SignUpTest">
    <failure type="java.lang.AssertionError" message="expected [Hi, Sazzad Hossain] but found [[]]">
      <![CDATA[java.lang.AssertionError: expected [Hi, Sazzad Hossain] but found [[]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at application.SignUpTest.createAccountSuccessTest(SignUpTest.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- createAccountSuccessTest -->
</testsuite> <!-- Default test -->
