<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-2NB5M8O" name="application.SignUpTest" tests="10" failures="1" timestamp="31 Aug 2019 12:50:01 GMT" time="27.754" errors="0">
  <testcase name="noEmailTest" time="1.070" classname="application.SignUpTest"/>
  <testcase name="shortPasswordTest" time="2.022" classname="application.SignUpTest"/>
  <testcase name="noPasswordTest" time="1.987" classname="application.SignUpTest"/>
  <testcase name="noConfirmPasswordTest" time="2.983" classname="application.SignUpTest"/>
  <testcase name="createAccountSuccessTest" time="7.065" classname="application.SignUpTest">
    <failure type="java.lang.AssertionError" message="expected [Hi, Sazzad Hossain] but found [[]]">
      <![CDATA[java.lang.AssertionError: expected [Hi, Sazzad Hossain] but found [[]]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at application.SignUpTest.createAccountSuccessTest(SignUpTest.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- createAccountSuccessTest -->
  <testcase name="noFirstNameTest" time="3.284" classname="application.SignUpTest"/>
  <testcase name="invalidEmailTest" time="2.585" classname="application.SignUpTest"/>
  <testcase name="passwordMismathwithConfirmPasswordTest" time="2.017" classname="application.SignUpTest"/>
  <testcase name="noLastNameTest" time="3.292" classname="application.SignUpTest"/>
  <testcase name="noInputTest" time="1.449" classname="application.SignUpTest"/>
</testsuite> <!-- application.SignUpTest -->
